---
- name: Ensure Redis is installed.
  package:
    name: "{{ redis_package }}"
    state: present
    enablerepo: "{{ redis_enablerepo }}"

- name: Add service file
  template:
    src: "{{ ansible_os_family }}/redis.service.j2"
    dest: "{{ redis_svc_path }}/{{ redis_svc_file }}"
  register: redis_service_file

- name: Reload redis service
  command: "{{ daemon_reload_cmd }}"
  when: redis_service_file | changed
